# Generated by Django 4.0.6 on 2022-07-13 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_alter_report_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='poster',
        ),
        migrations.AddField(
            model_name='report',
            name='poster',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
