# Generated by Django 4.0.6 on 2022-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_location_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
