# Generated by Django 4.0.6 on 2022-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_no_of_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default='9123456789', max_length=50, null=True),
        ),
    ]
